com.google.auto.service:* = 1.1.1
com.google.auto:* = 1.2.2
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.47.0
com.google.guava:guava = 33.6.0-jre
com.google.testing.compile:compile-testing = 0.23.0
com.palantir.goethe:goethe = 0.22.0
com.palantir.javapoet:javapoet = 0.15.0
org.assertj:* = 3.27.7
org.immutables:* = 2.12.2
org.junit.jupiter:* = 6.0.3
org.junit.platform:* = 6.0.3
